name: dslink_shell
description: DSLink Shell Requester
dependencies:
  dslink:
    git:
      url: https://github.com/IOT-DSA/sdk-dslink-dart.git
  syscall:
    git: https://github.com/DirectMyFile/syscall.git
  console:
    git: https://github.com/DirectMyFile/console.dart.git
executables:
  dsash: run
